# Puerto en el que correrá este microservicio
server:
  port: 8090

# Nombre de la aplicación. Será su identificador en Eureka.
spring:
  application:
    name: msvc-student

  # --- Configuración de la Base de Datos con MySQL ---
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/students_db
    username: root
    password: root1234

  # --- Configuración de JPA y Hibernate ---
  jpa:
    # 'create': Crea el esquema al iniciar. Borra los datos anteriores.
    hibernate:
      ddl-auto: create

    # Muestra en la consola las sentencias SQL que Hibernate ejecuta.
    show-sql: true
    database: mysql

    # Dialecto de SQL para MySQL 8 y superior.
    database-platform: org.hibernate.dialect.MySQL8Dialect

# --- Configuración del Cliente Eureka ---
eureka:
  instance:
    # El nombre del host que este microservicio usará para registrarse en Eureka.
    hostname: localhost
  client:
    # La URL del servidor Eureka donde este microservicio se registrará.
    service-url:
      defaultZone: http://localhost:8761/eureka/

